spring:
  datasource:
    url: jdbc:sqlite:./algoviz.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  output:
    ansi:
      enabled: always
  logging:
    level:
      root: INFO
      com.algoviz: DEBUG
      com.algoviz.util.WechatPayUtil: DEBUG
      com.algoviz.service.impl.PaymentServiceImpl: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.algoviz.entity
  
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 80

wechat:
  token: zhuxiaoyizxy123456789
  appid: wx82436d7e59251ede
  appsecret: 0f68f26ea80d9afcb3d6330accb66381
  encoding-aes-key: LPaoICvbhN6wcB9F5xllgxMaMIe1xEcdmA0kLIscBIF
  pay:
    appid: wx8834aa7ba60f283d
    mch-id: 1111047407
    mch-shortname: 亚茹
    api-v3-key: zhuxiaoyi1234567890ZHUXIAOYI1234
    cert-path: classpath:cert/apiclient_cert.pem
    private-key-path: classpath:cert/apiclient_key.pem
    cert-serial-no: 576B13569E2D30856E8A8017D496FE1BF072EEC0
    notify-url: http://dsaol.asia/api/payment/callback
    #notify-url: https://dsaol.asia/api/payment/callback
